/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import communication.Receiver;
import communication.Sender;
import domain.Coach;
import domain.Member;
import domain.TrainingSession;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.ClassType;
import logic.ShowTypeEnum;

/**
 *
 * @author Admin
 */
public class FrmMain extends javax.swing.JFrame {

    Socket socket;
    Sender sender;
    Receiver receiver;
    Coach user;
    
    public FrmMain(Coach c) {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.user = c;
        lblUser.setText(user.toString());
        try {
            socket = new Socket("127.0.0.1", 9000);
            sender = new Sender(socket);
            receiver = new Receiver(socket);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error connecting with server", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogOut = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddMemberItem = new javax.swing.JMenuItem();
        viewMembers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addCoach = new javax.swing.JMenuItem();
        viewCoaches = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addSession = new javax.swing.JMenuItem();
        viewSessions = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblUser.setText("jLabel1");

        jMenu1.setText("Member");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AddMemberItem.setText("Add new");
        AddMemberItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMemberItemActionPerformed(evt);
            }
        });
        jMenu1.add(AddMemberItem);

        viewMembers.setText("View");
        viewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMembersActionPerformed(evt);
            }
        });
        jMenu1.add(viewMembers);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Coach");

        addCoach.setText("Add new");
        addCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoachActionPerformed(evt);
            }
        });
        jMenu2.add(addCoach);

        viewCoaches.setText("View");
        viewCoaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoachesActionPerformed(evt);
            }
        });
        jMenu2.add(viewCoaches);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Training Session");

        addSession.setText("Add");
        addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSessionActionPerformed(evt);
            }
        });
        jMenu3.add(addSession);

        viewSessions.setText("View");
        viewSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSessionsActionPerformed(evt);
            }
        });
        jMenu3.add(viewSessions);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(btnLogOut))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMemberItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberItemActionPerformed
        Member member = new Member();
        JFrame frmAddMember = new FrmMember(socket,member,ShowTypeEnum.ADD,null);
        frmAddMember.setVisible(true);
        frmAddMember.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddMemberItemActionPerformed

    private void addCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoachActionPerformed
        Coach coach = new Coach();
        JFrame frmCoach = new FrmCoach(socket, coach, ShowTypeEnum.ADD, null);
        frmCoach.setVisible(true);
        frmCoach.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addCoachActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSessionActionPerformed
        TrainingSession session = new TrainingSession();
        JFrame frmTrainingSession = new FrmTrainingSession(socket,session, ShowTypeEnum.ADD,null);
        frmTrainingSession.setVisible(true);
        frmTrainingSession.pack();
        frmTrainingSession.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addSessionActionPerformed

    private void viewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMembersActionPerformed
        JFrame frmMember= new FrmViewAll(socket, ClassType.MEMBER);
        frmMember.setVisible(true);
        frmMember.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewMembersActionPerformed

    private void viewCoachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoachesActionPerformed
        JFrame frmCoach= new FrmViewAll(socket, ClassType.COACH);
        frmCoach.setVisible(true);
        frmCoach.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewCoachesActionPerformed

    private void viewSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSessionsActionPerformed
        JFrame frmSession= new FrmViewAll(socket, ClassType.TRAININGSESSION);
        frmSession.setVisible(true);
        frmSession.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewSessionsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Are you sure?", "", WIDTH, JOptionPane.YES_NO_OPTION);
        if(x == JOptionPane.YES_OPTION) {
            try {
                Communication.getInstance().logout(user);
                System.out.println(user);
                this.dispose();
                Communication.getInstance().connect();
                loginForm form = new loginForm();
                form.setVisible(true);
                form.pack();
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
       }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmMain(user).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddMemberItem;
    private javax.swing.JMenuItem addCoach;
    private javax.swing.JMenuItem addSession;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem viewCoaches;
    private javax.swing.JMenuItem viewMembers;
    private javax.swing.JMenuItem viewSessions;
    // End of variables declaration//GEN-END:variables
}
